<a href="https://colab.research.google.com/github/waraporn19/data_viz/blob/main/Quiz3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data_csv = pd.read_excel('/content/-.57-.58-1.xls', sheet_name=0,)
data_csv

                                         Unnamed: 0  ...                แบบ สขร. 1
0   สรุปผลการดำเนินการจัดซื้อในรอบเดือน ตุลาคม 2557  ...                       NaN
1        สำนักงานปลัดกระทรวงวิทยาศาสตร์และเทคโนโลยี  ...                       NaN
2                                               NaN  ...                       NaN
3                                             ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
4                                               ที่  ...                       NaN
5                                                 1  ...   เป็นผู้ให้บริการจำหน่าย
6                                                 2  ...   เป็นผู้ให้บริการจำหน่าย
7                                                 3  ...   เป็นผู้ให้บริการจำหน่าย
8                                                 4  ...   เป็นผู้ให้บริการจำหน่าย
9                                                 5  ...   เป็นผู้ให้บริการจำหน่าย
10                                                6  ...   เป็นผู้ให้บริการจำหน่าย
11                                                7  ...   เป็นผู้ให้บริการจำหน่าย
12                                                8  ...   เป็นผู้ให้บริการจำหน่าย
13                                                9  ...   เป็นผู้ให้บริการจำหน่าย
14                                               10  ...   เป็นผู้ให้บริการจำหน่าย
15                                               11  ...   เป็นผู้ให้บริการจำหน่าย
16                                               12  ...   เป็นผู้ให้บริการจำหน่าย
17                                               13  ...   เป็นผู้ให้บริการจำหน่าย
18                                               14  ...   เป็นผู้ให้บริการจำหน่าย
19                                               15  ...   เป็นผู้ให้บริการจำหน่าย
20                                              NaN  ...                แบบ สขร. 1
21  สรุปผลการดำเนินการจัดซื้อในรอบเดือน ตุลาคม 2557  ...                       NaN
22       สำนักงานปลัดกระทรวงวิทยาศาสตร์และเทคโนโลยี  ...                       NaN
23                                              NaN  ...                       NaN
24                                            ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
25                                              ที่  ...                       NaN
26                                               16  ...            เป็นผู้จำหน่าย
27                                               17  ...            เป็นผู้จำหน่าย
28                                               18  ...            เป็นผู้จำหน่าย
29                                               19  ...            เป็นผู้จำหน่าย
30                                               20  ...            เป็นผู้จำหน่าย
31                                               21  ...            เป็นผู้จำหน่าย
32                                               22  ...            เป็นผู้จำหน่าย
33                                               23  ...            เป็นผู้จำหน่าย
34                                               24  ...            เป็นผู้จำหน่าย
35                                               25  ...            เป็นผู้จำหน่าย
36                                               26  ...            เป็นผู้จำหน่าย
37                                               27  ...            เป็นผู้จำหน่าย
38                                               28  ...            เป็นผู้จำหน่าย
39                                               29  ...            เป็นผู้จำหน่าย

[40 rows x 9 columns]

เฉลย

In [37]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [39]:
import os
path = '/content/drive/My Drive/Dataviz_2021'
os.listdir(path)

['covid-19-daily_data_dictionary (1).xlsx',
 'pm-18-jan-2021.csv',
 '-.57-.58-1.xls']

In [41]:
file_path = os.path.join(path,'-.57-.58-1.xls')
print(file_path)

/content/drive/My Drive/Dataviz_2021/-.57-.58-1.xls

In [44]:
sale_df= pd.read_excel(file_path,sheet_name=0,skiprows=0,header=4)
sale_df

                                              ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
0                                               ที่  ...                       NaN
1                                                 1  ...   เป็นผู้ให้บริการจำหน่าย
2                                                 2  ...   เป็นผู้ให้บริการจำหน่าย
3                                                 3  ...   เป็นผู้ให้บริการจำหน่าย
4                                                 4  ...   เป็นผู้ให้บริการจำหน่าย
5                                                 5  ...   เป็นผู้ให้บริการจำหน่าย
6                                                 6  ...   เป็นผู้ให้บริการจำหน่าย
7                                                 7  ...   เป็นผู้ให้บริการจำหน่าย
8                                                 8  ...   เป็นผู้ให้บริการจำหน่าย
9                                                 9  ...   เป็นผู้ให้บริการจำหน่าย
10                                               10  ...   เป็นผู้ให้บริการจำหน่าย
11                                               11  ...   เป็นผู้ให้บริการจำหน่าย
12                                               12  ...   เป็นผู้ให้บริการจำหน่าย
13                                               13  ...   เป็นผู้ให้บริการจำหน่าย
14                                               14  ...   เป็นผู้ให้บริการจำหน่าย
15                                               15  ...   เป็นผู้ให้บริการจำหน่าย
16                                              NaN  ...                แบบ สขร. 1
17  สรุปผลการดำเนินการจัดซื้อในรอบเดือน ตุลาคม 2557  ...                       NaN
18       สำนักงานปลัดกระทรวงวิทยาศาสตร์และเทคโนโลยี  ...                       NaN
19                                              NaN  ...                       NaN
20                                            ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
21                                              ที่  ...                       NaN
22                                               16  ...            เป็นผู้จำหน่าย
23                                               17  ...            เป็นผู้จำหน่าย
24                                               18  ...            เป็นผู้จำหน่าย
25                                               19  ...            เป็นผู้จำหน่าย
26                                               20  ...            เป็นผู้จำหน่าย
27                                               21  ...            เป็นผู้จำหน่าย
28                                               22  ...            เป็นผู้จำหน่าย
29                                               23  ...            เป็นผู้จำหน่าย
30                                               24  ...            เป็นผู้จำหน่าย
31                                               25  ...            เป็นผู้จำหน่าย
32                                               26  ...            เป็นผู้จำหน่าย
33                                               27  ...            เป็นผู้จำหน่าย
34                                               28  ...            เป็นผู้จำหน่าย
35                                               29  ...            เป็นผู้จำหน่าย

[36 rows x 9 columns]

In [45]:
sale = pd.read_excel(file_path,sheet_name=1,skiprows=0,header=4)
sale

   ลำดับ  ... เหตุผลที่คัดเลือกโดยสรุป
0    ที่  ...                      NaN
1      1  ...  เป็นผู้ให้บริการจำหน่าย
2      2  ...           เป็นผู้จำหน่าย
3      3  ...           เป็นผู้จำหน่าย
4      4  ...           เป็นผู้จำหน่าย
..   ...  ...                      ...
76    56  ...                      NaN
77    57  ...                      NaN
78    58  ...                      NaN
79    59  ...                      NaN
80    60  ...                      NaN

[81 rows x 9 columns]

In [47]:
oct57 = pd.read_excel('-.57-.58-1.xls', sheet_name=0,header=4, skipfooter=20) #utf-8 -- latin1
oct57 = oct57.dropna()
oct57

   ลำดับ  ... เหตุผลที่คัดเลือกโดยสรุป
1      1  ...  เป็นผู้ให้บริการจำหน่าย
2      2  ...  เป็นผู้ให้บริการจำหน่าย
3      3  ...  เป็นผู้ให้บริการจำหน่าย
4      4  ...  เป็นผู้ให้บริการจำหน่าย
5      5  ...  เป็นผู้ให้บริการจำหน่าย
6      6  ...  เป็นผู้ให้บริการจำหน่าย
7      7  ...  เป็นผู้ให้บริการจำหน่าย
8      8  ...  เป็นผู้ให้บริการจำหน่าย
9      9  ...  เป็นผู้ให้บริการจำหน่าย
10    10  ...  เป็นผู้ให้บริการจำหน่าย
11    11  ...  เป็นผู้ให้บริการจำหน่าย
12    12  ...  เป็นผู้ให้บริการจำหน่าย
13    13  ...  เป็นผู้ให้บริการจำหน่าย
14    14  ...  เป็นผู้ให้บริการจำหน่าย
15    15  ...  เป็นผู้ให้บริการจำหน่าย

[15 rows x 9 columns]

In [50]:
oct57 = oct57.rename(columns={'Unnamed: 5' : 'ราคาเสนอ', 'Unnamed: 7': 'ราคาซื้อ'})
oct57

   ลำดับ  ... เหตุผลที่คัดเลือกโดยสรุป
1      1  ...  เป็นผู้ให้บริการจำหน่าย
2      2  ...  เป็นผู้ให้บริการจำหน่าย
3      3  ...  เป็นผู้ให้บริการจำหน่าย
4      4  ...  เป็นผู้ให้บริการจำหน่าย
5      5  ...  เป็นผู้ให้บริการจำหน่าย
6      6  ...  เป็นผู้ให้บริการจำหน่าย
7      7  ...  เป็นผู้ให้บริการจำหน่าย
8      8  ...  เป็นผู้ให้บริการจำหน่าย
9      9  ...  เป็นผู้ให้บริการจำหน่าย
10    10  ...  เป็นผู้ให้บริการจำหน่าย
11    11  ...  เป็นผู้ให้บริการจำหน่าย
12    12  ...  เป็นผู้ให้บริการจำหน่าย
13    13  ...  เป็นผู้ให้บริการจำหน่าย
14    14  ...  เป็นผู้ให้บริการจำหน่าย
15    15  ...  เป็นผู้ให้บริการจำหน่าย

[15 rows x 9 columns]

In [51]:
nov57 = pd.read_excel('-.57-.58-1.xls', sheet_name=0,header=4, skipfooter=20) #utf-8 -- latin1
oct57 = oct57.dropna()
oct57

   ลำดับ  ... เหตุผลที่คัดเลือกโดยสรุป
1      1  ...  เป็นผู้ให้บริการจำหน่าย
2      2  ...  เป็นผู้ให้บริการจำหน่าย
3      3  ...  เป็นผู้ให้บริการจำหน่าย
4      4  ...  เป็นผู้ให้บริการจำหน่าย
5      5  ...  เป็นผู้ให้บริการจำหน่าย
6      6  ...  เป็นผู้ให้บริการจำหน่าย
7      7  ...  เป็นผู้ให้บริการจำหน่าย
8      8  ...  เป็นผู้ให้บริการจำหน่าย
9      9  ...  เป็นผู้ให้บริการจำหน่าย
10    10  ...  เป็นผู้ให้บริการจำหน่าย
11    11  ...  เป็นผู้ให้บริการจำหน่าย
12    12  ...  เป็นผู้ให้บริการจำหน่าย
13    13  ...  เป็นผู้ให้บริการจำหน่าย
14    14  ...  เป็นผู้ให้บริการจำหน่าย
15    15  ...  เป็นผู้ให้บริการจำหน่าย

[15 rows x 9 columns]

## HW 8

In [52]:
import pandas as pd
import os

In [53]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [54]:
path = '/content/drive/My Drive/Dataviz_2021'

In [55]:
data_path = os.path.join(path,'-.57-.58-1.xls')

In [62]:
data1_df = pd.read_excel(data_path,header=4,skipfooter=20)
data1_df

   ลำดับ  ... เหตุผลที่คัดเลือกโดยสรุป
0    ที่  ...                      NaN
1      1  ...  เป็นผู้ให้บริการจำหน่าย
2      2  ...  เป็นผู้ให้บริการจำหน่าย
3      3  ...  เป็นผู้ให้บริการจำหน่าย
4      4  ...  เป็นผู้ให้บริการจำหน่าย
5      5  ...  เป็นผู้ให้บริการจำหน่าย
6      6  ...  เป็นผู้ให้บริการจำหน่าย
7      7  ...  เป็นผู้ให้บริการจำหน่าย
8      8  ...  เป็นผู้ให้บริการจำหน่าย
9      9  ...  เป็นผู้ให้บริการจำหน่าย
10    10  ...  เป็นผู้ให้บริการจำหน่าย
11    11  ...  เป็นผู้ให้บริการจำหน่าย
12    12  ...  เป็นผู้ให้บริการจำหน่าย
13    13  ...  เป็นผู้ให้บริการจำหน่าย
14    14  ...  เป็นผู้ให้บริการจำหน่าย
15    15  ...  เป็นผู้ให้บริการจำหน่าย

[16 rows x 9 columns]

In [63]:
data1_df = data1_df.rename(columns={'Unnamed: 5' : 'ราคาเสนอ', 'Unnamed: 7': 'ราคาซื้อ'})
data1_df #เปลี่ยนชื่อ colum

   ลำดับ  ... เหตุผลที่คัดเลือกโดยสรุป
0    ที่  ...                      NaN
1      1  ...  เป็นผู้ให้บริการจำหน่าย
2      2  ...  เป็นผู้ให้บริการจำหน่าย
3      3  ...  เป็นผู้ให้บริการจำหน่าย
4      4  ...  เป็นผู้ให้บริการจำหน่าย
5      5  ...  เป็นผู้ให้บริการจำหน่าย
6      6  ...  เป็นผู้ให้บริการจำหน่าย
7      7  ...  เป็นผู้ให้บริการจำหน่าย
8      8  ...  เป็นผู้ให้บริการจำหน่าย
9      9  ...  เป็นผู้ให้บริการจำหน่าย
10    10  ...  เป็นผู้ให้บริการจำหน่าย
11    11  ...  เป็นผู้ให้บริการจำหน่าย
12    12  ...  เป็นผู้ให้บริการจำหน่าย
13    13  ...  เป็นผู้ให้บริการจำหน่าย
14    14  ...  เป็นผู้ให้บริการจำหน่าย
15    15  ...  เป็นผู้ให้บริการจำหน่าย

[16 rows x 9 columns]

In [64]:
data2_df = pd.read_excel(data_path,sheet_name='พย.57',header=4,skipfooter=30)
data2_df

                                                ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
0                                                 ที่  ...                       NaN
1                                                   1  ...   เป็นผู้ให้บริการจำหน่าย
2                                                   2  ...            เป็นผู้จำหน่าย
3                                                   3  ...            เป็นผู้จำหน่าย
4                                                   4  ...            เป็นผู้จำหน่าย
5                                                   5  ...            เป็นผู้จำหน่าย
6                                                   6  ...            เป็นผู้จำหน่าย
7                                                   7  ...            เป็นผู้จำหน่าย
8                                                   8  ...            เป็นผู้จำหน่าย
9                                                   9  ...            เป็นผู้จำหน่าย
10                                                 10  ...            เป็นผู้จำหน่าย
11                                                 11  ...            เป็นผู้จำหน่าย
12                                                 12  ...            เป็นผู้จำหน่าย
13                                                 13  ...            เป็นผู้จำหน่าย
14                                                 14  ...            เป็นผู้จำหน่าย
15                                                 15  ...            เป็นผู้จำหน่าย
16                                                NaN  ...                แบบ สขร. 1
17  สรุปผลการดำเนินการจัดซื้อในรอบเดือน พฤษจิกายน ...  ...                       NaN
18         สำนักงานปลัดกระทรวงวิทยาศาสตร์และเทคโนโลยี  ...                       NaN
19                                                NaN  ...                       NaN
20                                              ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
21                                                ที่  ...                       NaN
22                                                 16  ...            เป็นผู้จำหน่าย
23                                                 17  ...            เป็นผู้จำหน่าย
24                                                 18  ...            เป็นผู้จำหน่าย
25                                                 19  ...            เป็นผู้จำหน่าย
26                                                 20  ...            เป็นผู้จำหน่าย
27                                                 21  ...            เป็นผู้จำหน่าย
28                                                 22  ...            เป็นผู้จำหน่าย
29                                                 23  ...            เป็นผู้จำหน่าย
30                                                 24  ...            เป็นผู้จำหน่าย
31                                                 25  ...            เป็นผู้จำหน่าย
32                                                 26  ...            เป็นผู้จำหน่าย
33                                                 27  ...            เป็นผู้จำหน่าย
34                                                 28  ...            เป็นผู้จำหน่าย
35                                                 29  ...            เป็นผู้จำหน่าย
36                                                 30  ...            เป็นผู้จำหน่าย
37                                                NaN  ...                       NaN
38                                                NaN  ...                แบบ สขร. 1
39  สรุปผลการดำเนินการจัดซื้อในรอบเดือน พฤศจิกายน ...  ...                       NaN
40         สำนักงานปลัดกระทรวงวิทยาศาสตร์และเทคโนโลยี  ...                       NaN
41                                                NaN  ...                       NaN
42                                              ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
43                                                ที่  ...                       NaN
44                                                 31  ...            เป็นผู้จำหน่าย
45                                                 32  ...            เป็นผู้จำหน่าย
46                                                 33  ...            เป็นผู้จำหน่าย
47                                                 34  ...            เป็นผู้จำหน่าย
48                                                 35  ...            เป็นผู้จำหน่าย
49                                                 36  ...            เป็นผู้จำหน่าย
50                                                 37  ...            เป็นผู้จำหน่าย

[51 rows x 9 columns]

In [65]:
data_a = pd.concat([data1_df,data2_df])
data_a

   ลำดับ  ... Unnamed: 7
0    ที่  ...        NaN
1      1  ...        NaN
2      2  ...        NaN
3      3  ...        NaN
4      4  ...        NaN
..   ...  ...        ...
46    33  ...        NaN
47    34  ...        NaN
48    35  ...        NaN
49    36  ...        NaN
50    37  ...        NaN

[67 rows x 11 columns]

In [66]:
data3_df = data_a.rename(columns={'Unnamed: 5':'ราคาเสนอ','Unnamed: 7':'ราคาาซื้อ'})
data3_df

   ลำดับ  ... ราคาาซื้อ
0    ที่  ...       NaN
1      1  ...       NaN
2      2  ...       NaN
3      3  ...       NaN
4      4  ...       NaN
..   ...  ...       ...
46    33  ...       NaN
47    34  ...       NaN
48    35  ...       NaN
49    36  ...       NaN
50    37  ...       NaN

[67 rows x 11 columns]